### ISSUE TITLE
Installation instructions for macOS

### ISSUE THREAD

**Issue by slel** [mraggi/discreture#1]
### Prerequisites

The prerequisites are:

- Apple's Developer tools

  - Check if already installed. The result should look like:

        $ xcode-select --version
        xcode-select version 2339.

  - If not installed, install it:

        $ xcode-select --install

We also need the GNU C++ compiler (the one offered by Apple might not work),
the CMake build tools, and the Boost library.

- We get those from Homebrew.

  - Check if Homebrew is already installed

        $ brew --version
        Homebrew 1.4.3
        Homebrew/homebrew-core (git revision 68ad7; last commit 2018-01-08)

  - If not, install it (see https://brew.sh), then run

        $ brew install gcc
        $ brew install cmake
        $ brew install boost

- Once this is done, check your tools.

  - Check version of `g++`, the result should look like:

        $ g++-7 --version
        g++-7 (Homebrew GCC 7.2.0) 7.2.0
        Copyright (C) 2017 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

  - Check version of cmake, the result should look like:

        $ cmake --version
        cmake version 3.9.1

  - Check that boost's facade iterator is present:

        $ ls /usr/local/include/boost/iterator | grep facade
        iterator_facade.hpp

### Building Discreture

Decide where to perform the build. In the example below we do this in
the user's home folder. To install elsewhere, replace the first `cd`
by `cd /path/to/elsewhere`, replacing `/path/to/elsewhere/` by the path
to the folder of your choice.

We change directory to the place we want, we clone the Discreture
repository from GitHub; this creates a folder called `discreture`.
We change to that folder, create a folder called `build`, change to
that folder, set the `CXX` environment variable to `g++-7` to use
the GNU C++ compiler we installed via Homebrew, run CMake then Make.

    $ cd
    $ git clone https://github.com/mraggi/discreture
    $ cd discreture
    $ mkdir build
    $ cd build
    $ export CXX=g++-7
    $ cmake .. -DBUILD_EXAMPLES=ON -DBUILD_BENCHMARKS=ON
    $ make

Once this is done, the list of files in the folder `build` should look like:

    $ ls
    CMakeCache.txt            combinations              discreture_benchmark      number_range
    CMakeFiles                combinations_reverse      dyck                      partitions
    Makefile                  combinations_tree         motzkin                   permutations
    cmake_install.cmake       combinations_tree_reverse multisets                 setpartitions

We can try out discreture's combinations enumerator:

    $ ./combinations 4 3  
    0 1 2
    0 1 3
    0 2 3
    1 2 3

and run the benchmarks

    $ ./discreture_benchmark

### Completing the installation

Finally, we complete the installation by running

    $ sudo make install

This might require typing an admin password.
As a result, the Discreture headers will be copied to
the appropriate location (by default, `/usr/local/include`).

**Comment by mraggi** [comment]
Thank you! Added some installation instructions for mac OS. As to not make it too long, I added a link to this ticket.
