### ISSUE TITLE
port to vcpkg

### ISSUE THREAD

**Issue by remz1337** [mraggi/discreture#11]
Just to let you know I'm trying to port this to vcpkg package manager. The PR is here:
https://github.com/microsoft/vcpkg/pull/15967

Once it's approved, it would be nice to include a line or 2 about it in the installation section of the readme :)

Thanks

**Comment by mraggi** [comment]
Awesome man. Let me know when it's done :)

Also, let me know if I have to make any changes (other than the README).

**Comment by remz1337** [comment]
Hey, just letting you know I've ported your library to vcpkg :). Once someone has vcpkg set up, it's as simple as `vcpkg install discreture`
