### ISSUE TITLE
Visual Studio little issue

### ISSUE THREAD

**Issue by bitwizardry** [mraggi/discreture#4]
Hi mraggi, I just tested some of your code examples on Visual Studio 2017, worked like a charm.
You just forgot to type the "typename" keyword before "decltype(d)::param_type;" in the FloatType random_real() function, in the Probability.hpp header. Thank you for your Excellent code work!
``

**Comment by mraggi** [comment]
Thank you! I've pushed they typename change. I don't know why my compiler
didn't complain :)

Good to know it works in visual studio too.

**Comment by slel** [comment]
Reference for the fix: https://github.com/mraggi/discreture/commit/831b8915f734344012c86d620df0520fae71e461

This issue can be closed.
